language: node_js
node_js:
- lts/*
before_install:
- npm install -g npm
- npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: change
sudo: required
cache:
  directories:
  - node_modules
addons:
  chrome: stable
deploy:
  provider: npm
  email: stdavis@utah.gov
  api_key:
    secure: TIcII6sVGw92KAmaBgwziw4hkQyCn1JU6N+OkFt6BpuRdp9q71I72xZkl6XDUmghc45zsr/4ujOixFBZQFi16dLyZNentg67BvEBEGuYmuauSNC3Nv3sYQx0e6wPgZz3LQZg6P5lFmNoQVgcu+Fs8yvvQCh3nxuK+fVqcwvNgcDqk4k0PAHMKwJ2CV2rgApjlOFEnJ7SMukTvzJ0dtwIFylVh09YzitEglg9EmnMuPdtXED3QJB2q34IqWY7m1R4K5AnuQdEaz7/71x74TtXk29YeH0BIEswCtbhU30t4LklvQZ9k9+sP/rJEfZenMPGxQyQPJ2OC0MIGoyANYFMWNUUm/c5ERrbcxVvNv0EzFe3hTKmgjBLfaVgmsnsocjlI5e4iqejcEAab7JDN72DUdigwXWuymW0KPchezsL6/e7QHSLnhUhcpliCxqgxgtF0Tj5w+yPneSqfym0Q8CuhG/fmSNi6c0rk03AuE93r3uBoSMYa/vTF8lOKexFY/jfKaqlCdusl3PIC37oqV1g8ORKxGjNrh1ZDesFFQJHdpI3yAGKojWAkIz40vPdOdJXUIAqZ7j3c0Y2C4nAhkYxYHypM9rFBtCwR+IXrQyolSJmqLoy26VWu++gN7vKIwizRB9M4u+/XjedprI3D5ZTMA7fYx186kqFTlEqs5egQxE=
  on:
    tags: true
    repo: agrc-widgets/sherlock
